sudo: required

language: java

services:
 - docker
 
before_install:
  - docker build -t green .
 
script:
 - docker run green /bin/sh -c "ant && ant test"
 - cat bin/junit/TEST-za.ac.sun.cs.green.EntireSuite.xml
